on:
  workflow_run:
    types:
      - completed
    workflows:
      - Create release
  workflow_dispatch:
name: Deploy to prod
jobs:
  web-deploy:
    name: Deploy
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v4

    - name: 'Download artifact'
      if: ${{ github.event_name == 'workflow_run' }}
      uses: actions/github-script@v8
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
             owner: context.repo.owner,
             repo: context.repo.repo,
             run_id: context.payload.workflow_run.id,
          });
          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "tag"
          })[0];
          let download = await github.rest.actions.downloadArtifact({
             owner: context.repo.owner,
             repo: context.repo.repo,
             artifact_id: matchArtifact.id,
             archive_format: 'zip',
          });
          const fs = require('fs');
          const path = require('path');
          const temp = '${{ runner.temp }}/artifacts';
          if (!fs.existsSync(temp)){
            fs.mkdirSync(temp);
          }
          fs.writeFileSync(path.join(temp, 'tag.zip'), Buffer.from(download.data));
    - name: 'Unzip artifact'
      id: get_tag
      if: ${{ github.event_name == 'workflow_run' }}
      run: |
        unzip "${{ runner.temp }}/artifacts/tag.zip" -d "${{ runner.temp }}/artifacts"
        echo "tag=$(cat ${{ runner.temp }}/artifacts" >> $GITHUB_OUTPUT
    - name: Checkout generated release
      if: ${{ github.event_name == 'workflow_run' }}
      uses: actions/checkout@v4
      with:
        ref: refs/tags/${{ steps.get_tag.outputs.tag }}
    - name: Get reSsg
      uses: jaxxstorm/action-install-gh-release@v2.1.0
      with:
        repo: rebenkoy/reSsg
    - name: Run reSsg
      run: reSsg build --output=/tmp/output
    - name: SFTP upload
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ vars.URL }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 2022
        uploads: |
          /tmp/output => ./
