on:
  push:
    branches:
      master
  workflow_dispatch:
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get reSsg
      uses: jaxxstorm/action-install-gh-release@v2.1.0
      with:
        repo: rebenkoy/reSsg
    - name: Run reSsg
      run: reSsg build --build.prefix=r-${{ github.sha }} --build.output=/tmp/output
    - name: SFTP upload
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ vars.URL }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 2022
        uploads: |
          /tmp/output => ./
