on:
  push:
    branches:
      - 'updates'
  workflow_dispatch:
name: Deploy to test
jobs:
  web-deploy:
    name: Deploy
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set short sha
        id: vars
        run: echo "prefix=r-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set comment text
        id: comment_gen
        run: |
          echo 'comment="\n[![Preview Badge]](${{ vars.PREVIEW_URL }}/${{ steps.vars.outputs.prefix }}/)\n\n[Preview Badge]: https://img.shields.io/badge/>>Preview<<-1f883d?style=for-the-badge"' >> $GITHUB_OUTPUT
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          PULL_REQUEST_TITLE: "Updates"
          PULL_REQUEST_BODY: ${{ steps.comment_gen.outputs.comment }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: ""
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_UPDATE: true
        id: pr
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.pr.outputs.pull_request_number }}
          body: ${{ steps.comment_gen.outputs.comment }}
      - name: Get reSsg
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: rebenkoy/reSsg
      - name: Run reSsg
        run: reSsg build --output=/tmp/output
      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ vars.URL }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 2022
          uploads: |
            /tmp/output => ./${{ steps.vars.outputs.prefix }}